---
default: &default
  project_name: Shaf Demo API

  public_folder: frontend/assets
  views_folder: frontend/views
  documents_dir: doc/api
  migrations_dir: db/migrations
  fixtures_dir: spec/fixtures
  paginate_per_page: 10
  http_cache: on
  http_cache_max_age_long: 86400 # 60 * 60 * 24 = 1 day
  http_cache_max_age_short: 3600 #      60 * 60 = 1 hour
  hostname: localhost
  protocol: http
  port: 3000
  default_authentication_realm: demo

production:
  <<: *default
  port: <%= ENV.fetch('PORT', 443) %>
  base_uri: https://shaf-blog-demo.herokuapp.com

development:
  <<: *default

test:
  <<: *default
  port: 3030
